export const ADD_LIST = 'ADD_LIST';
export const ADD_CARD_TO_LIST = 'ADD_CARD_TO_LIST';
export const MOVE_CARD_TO_LIST = 'MOVE_CARD_TO_LIST';
export const REMOVE_LIST = 'REMOVE_LIST';
export const REMOVE_CARD_FROM_LIST = 'REMOVE_CARD_FROM_LIST';
